### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of null

### ISSUE THREAD

**Issue by samunt** [armin-pfaeffle/sass-autocompile#105]
Has been working fine for months. this morning I tried to autocompile and got this error. tried reinstalling, rebooting, but to no avail
`/Users/sammy/.atom/packages/sass-autocompile/lib/sass-autocompile-view.coffee:143
TypeError: Cannot read property 'file' of null
    at SassAutocompileView.module.exports.SassAutocompileView.erroneousCompilation (/Users/sammy/.atom/packages/sass-autocompile/lib/sass-autocompile-view.coffee:143:24)
    at /Users/sammy/.atom/packages/sass-autocompile/lib/sass-autocompile.coffee:451:34
    at Function.module.exports.Emitter.simpleDispatch (/Users/sammy/.atom/packages/sass-autocompile/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/sammy/.atom/packages/sass-autocompile/node_modules/event-kit/lib/emitter.js:125:28)
    at NodeSassCompiler.module.exports.NodeSassCompiler.onCompiled (/Users/sammy/.atom/packages/sass-autocompile/lib/compiler.coffee:602:26)
    at /Users/sammy/.atom/packages/sass-autocompile/lib/compiler.coffee:563:30
    at /Users/sammy/.atom/packages/sass-autocompile/lib/compiler.coffee:469:21
    at /Users/sammy/.atom/packages/sass-autocompile/lib/compiler.coffee:489:21
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)`

**Comment by HannahSchott** [comment]
Were you able to fix the problem I got the same issue?

TypeError: Cannot read property 'file' of null
    at SassAutocompileView.module.exports.SassAutocompileView.erroneousCompilation (/Users/Hannah/.atom/packages/sass-autocompile/lib/sass-autocompile-view.coffee:143:24)
    at /Users/Hannah/.atom/packages/sass-autocompile/lib/sass-autocompile.coffee:451:34
    at Function.module.exports.Emitter.simpleDispatch (/Users/Hannah/.atom/packages/sass-autocompile/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/Hannah/.atom/packages/sass-autocompile/node_modules/event-kit/lib/emitter.js:125:28)
    at NodeSassCompiler.module.exports.NodeSassCompiler.onCompiled (/Users/Hannah/.atom/packages/sass-autocompile/lib/compiler.coffee:602:26)
    at /Users/Hannah/.atom/packages/sass-autocompile/lib/compiler.coffee:563:30
    at /Users/Hannah/.atom/packages/sass-autocompile/lib/compiler.coffee:469:21
    at /Users/Hannah/.atom/packages/sass-autocompile/lib/compiler.coffee:489:21
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by samunt** [comment]
No, unfortunately not. It affected all of my apps. I switched to Gulp after
a day of trying g to solve the issue

**Comment by HannahSchott** [comment]
Oh Boy... ok thanx though for the quick answer :)

**Comment by armin-pfaeffle** [comment]
Hey together! Sorry for my late answer, having a lot to do at the moment.

Hm... Can you give me your node-sass verison? Go to terminal and enter `node-sass --version`.

**Comment by samunt** [comment]
node-sass 3.10.1 and libsass 3.3.5

**Comment by armin-pfaeffle** [comment]
I nearly have the same version. My libsass 3.3.6.

**Comment by armin-pfaeffle** [comment]
Can you give me a description (or perhaps the corresponding files), so I can try to reproduce this error?!
