### ISSUE TITLE
SASS AutoCompile: Error while compiling

### ISSUE THREAD

**Issue by 9o** [armin-pfaeffle/sass-autocompile#13]
When using 0.7.5 with 
```
node-sass	3.2.0	(Wrapper)	[JavaScript]
libsass  	3.2.5	(Sass Compiler)	[C/C++]
```

I get the following error:
```
/Users/henry/.nvm/versions/node/v0.12.7/lib/node_modules/node-sass/lib/extensions.js:148
    throw new Error(['`libsass` bindings not found in ', binaryPath, '. Try re
          ^
Error: `libsass` bindings not found in /Users/henry/.nvm/versions/node/v0.12.7/lib/node_modules/node-sass/vendor/darwin-x64-11/binding.node. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath (/Users/henry/.nvm/versions/node/v0.12.7/lib/node_modules/node-sass/lib/extensions.js:148:11)
    at Object.<anonymous> (/Users/henry/.nvm/versions/node/v0.12.7/lib/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/henry/.nvm/versions/node/v0.12.7/lib/node_modules/node-sass/lib/render.js:9:12)
    at Module._compile (module.js:456:26)
```

`/Users/henry/.nvm/versions/node/v0.12.7/lib/node_modules/node-sass/vendor/darwin-x64-11/` Does not exsist, although `... r/darwin-x64-14/` does. When I change the path to reflect this I get the following new error.
```
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/henry/.nvm/versions/node/v0.12.7/lib/node_modules/node-sass/vendor/darwin-x64-11/binding.node
  Expected in: flat namespace

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/henry/.nvm/versions/node/v0.12.7/lib/node_modules/node-sass/vendor/darwin-x64-11/binding.node
  Expected in: flat namespace
```

**Comment by armin-pfaeffle** [comment]
I think, that's a node problem. Have you tried to remove node-sass and reinstall it?
```
// Remove
npm uninstall node-sass -g

// Install
npm install node-sass -g
```

**Comment by armin-pfaeffle** [comment]
Hey!

Any news about your problem? Else I will close it.
