### ISSUE TITLE
Failed to activate the sass-autocompile package

### ISSUE THREAD

**Issue by entepe85** [armin-pfaeffle/sass-autocompile#17]
[Enter steps to reproduce below:]

1. Install sass-autocompile update 0.9.0
2. Atom throws an error

**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.5
**Thrown From**: [sass-autocompile](https://github.com/armin-pfaeffle/sass-autocompile) package, v0.9.0

### Stack Trace

Failed to activate the sass-autocompile package

```
At Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.updateMenuItems (/Users/nils/.atom/packages/sass-autocompile/lib/sass-autocompile.coffee:197:53)
    at /Users/nils/.atom/packages/sass-autocompile/lib/sass-autocompile.coffee:188:13
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:568:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
    at Object.module.exports.registerConfigObserver (/Users/nils/.atom/packages/sass-autocompile/lib/sass-autocompile.coffee:185:60)
    at Object.module.exports.activate (/Users/nils/.atom/packages/sass-autocompile/lib/sass-autocompile.coffee:166:5)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:224:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)
```

### Commands

```
     -0:40.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-chester-atom-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".DS_Store",
      ".git",
      ".svn"
    ],
    "disabledPackages": [
      "feedback",
      "metrics",
      "styleguide",
      "welcome",
      "snippets",
      "package-generator",
      "dev-live-reload",
      "linter-jshint",
      "emmet",
      "htmlhint",
      "deprecation-cop",
      "jekyll",
      "atom-color-highlight",
      "git-tab-status"
    ],
    "projectHome": "/Users/nils/Desktop/Work/",
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ]
  },
  "sass-autocompile": {
    "sourceMap": true
  }
}
```

### Installed Packages

```coffee
# User
atom-minify, v0.3.1
autoclose-html, v0.18.0
autocomplete-php, v0.3.7
bezier-curve-editor, v0.7.2
chester-atom-syntax, v0.1.1
color-picker, v2.0.11
file-icons, v1.6.9
fold-functions, v0.3.1
git-log, v0.4.1
grammar-token-limit, v0.1.1
highlight-selected, v0.10.1
jslint, v1.4.0
language-htaccess, v0.1.1
less-autocompile, v1.0.0
minimap, v4.13.2
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.0
minimap-pigments, v0.1.6
pigments, v0.13.2
project-manager, v2.0.1
sass-autocompile, v0.9.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by armin-pfaeffle** [comment]
Can you try to uninstall und reinstall my package? I think, something went wrong with the internal Atom cache.

**Comment by entepe85** [comment]
Uninstalling and reinstalling unfortunately brought up the same error message.

**Comment by armin-pfaeffle** [comment]
Can you try to execute this command in your terminal?
```
apm rebuild-module-cache
```
Does this fix your problem?

**Comment by entepe85** [comment]
Yes, that worked! Thank you very much.
