### ISSUE TITLE
Uncaught SyntaxError: Unexpected token /

### ISSUE THREAD

**Issue by LasseRafn** [armin-pfaeffle/sass-autocompile#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: [sass-autocompile](https://github.com/armin-pfaeffle/sass-autocompile) package, v0.3.1

### Stack Trace

Uncaught SyntaxError: Unexpected token /

```
At file:///Applications/Atom.app/Contents/Resources/app/static/index.html?loadSettings=%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3Anull%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.186.0%22%2C%22shellLoadTime%22%3A174%2C%22initialPaths%22%3A%5B%5D%7D:1

SyntaxError: Unexpected token /
  at Object.parse (native)
  at /Users/lasserafn/.atom/packages/sass-autocompile/lib/sass-autocompile-view.coffee:158:38
  at ChildProcess.exithandler (child_process.js:756:5)
  at ChildProcess.emit (events.js:119:17)
  at maybeClose (child_process.js:1013:16)
  at Socket.<anonymous> (child_process.js:1181:11)
  at Socket.emit (events.js:116:17)
  at Pipe.close (net.js:477:12)

```

### Commands

```
  2x -0:28.8 core:save (atom-text-editor.editor.is-focused)
     -0:27.5 core:backspace (atom-text-editor.editor.is-focused)
  4x -0:27.3 core:save (atom-text-editor.editor.is-focused)
     -0:03.9 core:move-right (atom-text-editor.editor.mini)
     -0:03.8 core:move-left (atom-text-editor.editor.mini)
  3x -0:03.5 core:move-right (atom-text-editor.editor.mini)
     -0:03.0 core:select-right (atom-text-editor.editor.mini)
     -0:02.7 core:confirm (atom-text-editor.editor.mini)
     -0:01.1 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "atom-bootstrap3"
    ]
  },
  "sass-autocompile": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.2.0
atom-beautify, v0.21.4
atom-handlebars, v0.4.0
autocomplete-plus, v2.4.1
color-picker, v1.4.4
emmet, v2.3.4
language-SCSS, v0.2.0
language-spacebars, v0.2.2
less-autocompile, v1.0.0
less-than-slash, v0.3.4
linter, v0.12.0
meteor-api, v2.12.0
minimap, v4.5.0
pretty-json, v0.3.2
project-manager, v1.15.5
sass-autocompile, v0.3.1
seti-syntax, v0.3.3
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by armin-pfaeffle** [comment]
Thanks for you report!

I improved the error handling a lil' bit, so the exception you posted should not occur any more.

But have a look at the [requirements](https://github.com/armin-pfaeffle/sass-autocompile#requirements). Have you installed node.js and node-sass (global installation)?

**Comment by LasseRafn** [comment]
Thanks you! 

Yes I have used the command to install (-g), but I can try reinstalling :-)
