### ISSUE TITLE
Error when loading sass-autocompile

### ISSUE THREAD

**Issue by FirstZero** [armin-pfaeffle/sass-autocompile#21]
**Atom Version**: 1.0.15
**System**: linux 4.1.7_2
**Thrown From**: [sass-autocompile](https://github.com/armin-pfaeffle/sass-autocompile) package, v0.10.0

### Stack Trace

Failed to load the sass-autocompile package

```
At Cannot find module './File'

Error: Cannot find module './File'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/home/zero/.atom/packages/sass-autocompile/lib/sass-autocompile.coffee:7:8)
    at Object.<anonymous> (/home/zero/.atom/packages/sass-autocompile/lib/sass-autocompile.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  },
  "sass-autocompile": {}
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.19.0
go-plus, v3.5.1
less-autocompile, v1.0.0
linter, v1.6.0
linter-golinter, v1.0.0
linter-htmlhint, v0.1.1
linter-scss-lint, v2.0.0
minimap, v4.13.3
monokai-seti, v0.7.0
sass-autocompile, v0.10.0
save-session, v0.15.7
seti-icons, v0.4.5
seti-ui, v0.8.0

# Dev
No dev packages
```

**Comment by armin-pfaeffle** [comment]
Hey!

There was an error in the version before that leads to the update problem. Please enter this in your terminal and restart atom. Then everything should work fine:

```
apm rebuild-module-cache
```

**Comment by FirstZero** [comment]
Thank you for reply!

Of course I tried that already, but if I restart it, the error just shows up again.
    `Cannot find module './File'`

**Comment by armin-pfaeffle** [comment]
Oh... I think that's a case sensitive problem...

Please try latest version 0.10.1 which I published right now.

**Comment by FirstZero** [comment]
Ye, happens..
Looks like this fixed it, everything works fine the way it should now.
So I am gonna close this issue!
