### ISSUE TITLE
Uncaught TypeError: Cannot read property 'activateItem' of undefined

### ISSUE THREAD

**Issue by lucamazzali** [armin-pfaeffle/sass-autocompile#30]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [sass-autocompile](https://github.com/armin-pfaeffle/sass-autocompile) package, v0.10.6

### Stack Trace

Uncaught TypeError: Cannot read property 'activateItem' of undefined

```
At /Users/net2b/.atom/packages/sass-autocompile/lib/sass-autocompile-view.coffee:247

TypeError: Cannot read property 'activateItem' of undefined
  at SassAutocompileView.module.exports.SassAutocompileView.openNodeSassOutput (/Users/net2b/.atom/packages/sass-autocompile/lib/sass-autocompile-view.coffee:247:21)
  at HTMLSpanElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
  at HTMLSpanElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLSpanElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -2:45.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:40.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:22.8.0 core:select-up (atom-text-editor.editor.is-focused)
     -2:22.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:21.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:29.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:27.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:27.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:27.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:25.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:25.6.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:16.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "sass-autocompile": {
    "includePath": "../css/"
  }
}
```

### Installed Packages

```coffee
# User
sass-autocompile, v0.10.6

# Dev
No dev packages
```

**Comment by armin-pfaeffle** [comment]
Hey! Thanks for your report. I fixed this bug with version 0.10.7 which I published right now.
