### ISSUE TITLE
Uncaught TypeError: Cannot read property 'emit' of null

### ISSUE THREAD

**Issue by mefynn** [armin-pfaeffle/sass-autocompile#31]
1. ... tried to save the scss

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [sass-autocompile](https://github.com/armin-pfaeffle/sass-autocompile) package, v0.10.7

### Stack Trace

Uncaught TypeError: Cannot read property 'emit' of null

```
At /Users/fynn/.atom/packages/sass-autocompile/lib/compiler.coffee:393

TypeError: Cannot read property 'emit' of null
  at NodeSassCompiler.module.exports.NodeSassCompiler.doCompile (/Users/fynn/.atom/packages/sass-autocompile/lib/compiler.coffee:393:21)
  at /Users/fynn/.atom/packages/sass-autocompile/lib/compiler.coffee:76:22
  at /Users/fynn/.atom/packages/sass-autocompile/lib/inline-parameters.coffee:20:25
  at ReadStream.<anonymous> (/Users/fynn/.atom/packages/sass-autocompile/lib/inline-parameters.coffee:43:21)
  at emitOne (events.js:77:13)
  at ReadStream.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at ReadStream.Readable.push (_stream_readable.js:110:10)
  at onread (fs.js:1749:12)
  at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)

```

### Commands

```
     -9:41.3.0 core:save (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -9:08.6.0 sass-autocompile:toggle-output-style-compressed (atom-text-editor.editor.is-focused)
     -9:00.1.0 core:save (atom-text-editor.editor.is-focused)
     -8:44.7.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -8:43.6.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -8:42.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -8:40.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -8:40.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -8:38.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:30.9.0 core:cancel (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:01.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "sass-compiler",
      "atom-minify",
      "autocomplete-sass"
    ]
  },
  "sass-autocompile": {
    "directlyJumpToError": true,
    "checkOutputFileAlreadyExists": true,
    "compileCompressed": false
  }
}
```

### Installed Packages

```coffee
# User
Sass-Syntax-Highlight, v0.1.1
atom-beautify, v0.28.15
color-picker, v2.0.13
emmet, v2.3.13
minimap, v4.15.0
sass-autocompile, v0.10.7

# Dev
No dev packages
```

**Comment by armin-pfaeffle** [comment]
Fixed with version 0.10.8!
