### ISSUE TITLE
Command failed

### ISSUE THREAD

**Issue by Amstramgram** [armin-pfaeffle/sass-autocompile#40]
hi,

i update my npm and node for latest version and i have this error when i save my main.sass. 

```
/usr/local/lib/node_modules/node-sass/lib/extensions.js:150
    throw new Error([
    ^
Error: The `libsass` binding was not found in /usr/local/lib/node_modules/node-sass/vendor/darwin-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/usr/local/lib/node_modules/node-sass/lib/extensions.js:150:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-sass/lib/render.js:9:12)
    at Module._compile (module.js:435:26)
```

so i run `npm rebuild node-sass` and in my terminal i have 
```
> node-sass@3.4.2 install /Users/JulienMiclo/node_modules/node-sass
> node scripts/install.js
> node-sass@3.4.2 postinstall /Users/myname/node_modules/node-sass
> node scripts/build.js ` /Users/myname/node_modules/node-sass/vendor/darwin-x64-46/binding.node ` exists. testing binary.
Binary is fine; exiting.
node-sass@3.4.2 /Users/myname/node_modules/node-sass
```

Can you tell me why and how i can for solved this ?

thank

**Comment by Amstramgram** [comment]
oh i didn't install sass globaly i forgot "-g"

**Comment by armin-pfaeffle** [comment]
That was one of the fastest close I've every seen ;)

**Comment by Amstramgram** [comment]
Sorry, I panicked for no reasons.

**Comment by armin-pfaeffle** [comment]
No problem! It's not that an easy installation like only downloading a plugin ;) It's one of the not so nice things of my plugin. But hey... it works :dancer:
