### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by cjrh** [armin-pfaeffle/sass-autocompile#5]
[Enter steps to reproduce below:]

1. Installed html-preview
2. Hit CTRL-P inside an HTML file

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [sass-autocompile](https://github.com/armin-pfaeffle/sass-autocompile) package, v0.6.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:128

TypeError: undefined is not a function
  at SassAutocompileView.module.exports.SassAutocompileView.compile (/Users/calebhattingh/.atom/packages/sass-autocompile/lib/sass-autocompile-view.coffee:93:27)
  at /Users/calebhattingh/.atom/packages/sass-autocompile/lib/sass-autocompile-view.coffee:49:22
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:917:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:899:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:554:26)
  at AtomHtmlPreviewView.module.exports.AtomHtmlPreviewView.renderHTMLCode (/Users/calebhattingh/.atom/packages/atom-html-preview/lib/atom-html-preview-view.coffee:95:76)
  at AtomHtmlPreviewView.module.exports.AtomHtmlPreviewView.renderHTML (/Users/calebhattingh/.atom/packages/atom-html-preview/lib/atom-html-preview-view.coffee:92:8)
  at /Users/calebhattingh/.atom/packages/atom-html-preview/lib/atom-html-preview.coffee:54:25
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:516:49
  at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -2:54.1.0 core:move-down (atom-text-editor.editor)
  3x -2:52.9.0 core:backspace (atom-text-editor.editor)
     -2:50.8.0 core:save (atom-text-editor.editor)
     -2:27.8.0 core:move-up (atom-text-editor.editor)
     -2:22.1.0 command-palette:toggle (atom-text-editor.editor)
  4x -2:19.2.0 core:move-down (atom-text-editor.editor.mini)
     -2:18.1.0 core:confirm (atom-text-editor.editor.mini)
     -2:18.1.0 settings-view:uninstall-packages (atom-text-editor.editor)
  2x -2:10.3.0 core:confirm (atom-text-editor.editor.mini)
     -0:06.9.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -0:02.0 atom-html-preview:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  },
  "sass-autocompile": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.24.1
atom-html-preview, v0.1.6
autoclose-html, v0.15.0
autocomplete-emojis, v2.2.0
autocomplete-html, v0.5.0
color-gutter, v0.4.1
color-picker, v1.7.0
compass, v0.7.5
html2haml, v0.8.0
language-cython, v0.3.0
language-haml, v0.20.0
language-python-django-templates, v0.1.0
linter, v0.12.1
linter-haml, v0.1.1
linter-pep8, v0.1.0
linter-pylint, v0.2.1
markdown-preview-plus, v1.3.0
markdown-scroll-sync, v0.3.3
markdown-stream, v0.6.0
markdown-writer, v1.1.2
minimap, v4.7.6
sass-autocompile, v0.6.1
sass-watch, v0.3.1
script, v2.19.0
seti-syntax, v0.4.0
travis-ci-status, v0.13.0
virtualenv, v0.6.2

# Dev
No dev packages
```

**Comment by armin-pfaeffle** [comment]
Pleas try new version 0.6.2. This issue should be fixed now.

**Comment by armin-pfaeffle** [comment]
It seems everything is working, so I close this issue.
