### ISSUE TITLE
Uncaught TypeError: Cannot read property 'compileOnSave' of undefined

### ISSUE THREAD

**Issue by sladage** [armin-pfaeffle/sass-autocompile#58]
[Enter steps to reproduce below:]

1. Use first line comment "//main: <filename>" without file extension

**Atom Version**: 1.5.4
**System**: linux 4.4.3-1-ARCH
**Thrown From**: [sass-autocompile](https://github.com/armin-pfaeffle/sass-autocompile) package, v0.12.3

### Stack Trace

Uncaught TypeError: Cannot read property 'compileOnSave' of undefined

```
At /usr/share/atom/resources/app.asar/src/pane.js:825

TypeError: Cannot read property 'compileOnSave' of undefined
    at NodeSassCompiler.module.exports.NodeSassCompiler.prohibitCompilationOnSave (/home/stefan/.atom/packages/sass-autocompile/lib/compiler.coffee:113:18)
    at /home/stefan/.atom/packages/sass-autocompile/lib/compiler.coffee:50:36
    at /home/stefan/.atom/packages/sass-autocompile/lib/helper/inline-parameters-parser.coffee:24:21
    at InlineParameterParser.module.exports.InlineParameterParser.readFirstLine (/home/stefan/.atom/packages/sass-autocompile/lib/helper/inline-parameters-parser.coffee:34:13)
    at InlineParameterParser.module.exports.InlineParameterParser.parse (/home/stefan/.atom/packages/sass-autocompile/lib/helper/inline-parameters-parser.coffee:22:14)
    at NodeSassCompiler.module.exports.NodeSassCompiler._compile (/home/stefan/.atom/packages/sass-autocompile/lib/compiler.coffee:47:25)
    at /home/stefan/.atom/packages/sass-autocompile/lib/compiler.coffee:87:22
    at InlineParameterParser.module.exports.InlineParameterParser.parseFirstLineParameter (/home/stefan/.atom/packages/sass-autocompile/lib/helper/inline-parameters-parser.coffee:66:17)
    at InlineParameterParser.module.exports.InlineParameterParser.parse (/home/stefan/.atom/packages/sass-autocompile/lib/helper/inline-parameters-parser.coffee:18:14)
    at NodeSassCompiler.module.exports.NodeSassCompiler._compile (/home/stefan/.atom/packages/sass-autocompile/lib/compiler.coffee:47:25)
    at NodeSassCompiler.module.exports.NodeSassCompiler.compile (/home/stefan/.atom/packages/sass-autocompile/lib/compiler.coffee:33:10)
    at Object.module.exports.compile (/home/stefan/.atom/packages/sass-autocompile/lib/sass-autocompile.coffee:449:19)
    at /home/stefan/.atom/packages/sass-autocompile/lib/sass-autocompile.coffee:456:22
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:630:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:545:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:42.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:42.9.0 editor:indent (atom-text-editor.editor.is-focused)
  5x -0:38.5.0 core:backspace (atom-text-editor.editor.is-focused)
  5x -0:30.1.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:26.6.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:26.5.0 core:move-left (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:26 core:move-up (atom-text-editor.editor.is-focused)
     -0:25.6.0 core:move-left (atom-text-editor.editor.is-focused)
  4x -0:25.1.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:17.7.0 core:move-right (atom-text-editor.editor.is-focused)
  6x -0:17 core:select-left (atom-text-editor.editor.is-focused)
  2x -0:08.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:05.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:05.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.3.0 core:copy (atom-text-editor.editor.is-focused)
     -0:00.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "sass-watch"
    ],
    "followSymlinks": false
  },
  "sass-autocompile": {
    "compileFiles": "Only with first-line-comment"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.26
atom-toolbar, v0.1.6
color-picker, v2.1.1
dartlang, v0.6.4
flutter, v0.2.1
language-rust, v0.4.6
linter, v1.11.3
linter-rust, v0.4.1
sass-autocompile, v0.12.3
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by armin-pfaeffle** [comment]
Fixed with 0.12.4

Thanks!
