### ISSUE TITLE
Failed to load the sass-autocompile package

### ISSUE THREAD

**Issue by sinejoe** [armin-pfaeffle/sass-autocompile#6]
[Enter steps to reproduce below:]

1. Update Atom Editor to 0.196
2. Open Atom Editor [screenshot](http://cl.ly/aqhj)

**Atom Version**: 0.196.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [sass-autocompile](https://github.com/armin-pfaeffle/sass-autocompile) package, v0.6.2

### Stack Trace

Failed to load the sass-autocompile package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/joe/.atom/packages/sass-autocompile/lib/sass-autocompile-view.coffee:4:199)
    at /Users/joe/.atom/packages/sass-autocompile/lib/sass-autocompile-view.coffee:9:5
    at Object.<anonymous> (/Users/joe/.atom/packages/sass-autocompile/lib/sass-autocompile-view.coffee:495:5)
    at Object.<anonymous> (/Users/joe/.atom/packages/sass-autocompile/lib/sass-autocompile-view.coffee:497:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai-dark"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".hg",
      "*.pyc",
      "node_modules"
    ],
    "projectHome": "/var/www"
  },
  "sass-autocompile": {
    "compress": true
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
atom-spotify, v1.2.0
auto-update-packages, v0.2.2
autocomplete-css, v0.6.0
autocomplete-html, v0.6.0
autocomplete-plus, v2.12.1
autocomplete-plus-jedi, v0.0.9
django-templates, v0.4.0
file-types, v0.3.0
language-liquid, v0.2.0
language-nunjucks, v1.3.0
minifier, v0.2.0
monokai-dark, v1.3.0
revert-buffer, v0.5.0
sass-autocompile, v0.6.2
save-session, vundefined
text-manipulation, v0.6.0

# Dev
No dev packages
```

**Comment by armin-pfaeffle** [comment]
Hey! Thanks for your report! Now it should work.
