### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getURI' of undefined

### ISSUE THREAD

**Issue by sassplus** [armin-pfaeffle/sass-autocompile#67]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Unknown Windows Version
**Thrown From**: [sass-autocompile](https://github.com/armin-pfaeffle/sass-autocompile) package, v0.12.6

### Stack Trace

Uncaught TypeError: Cannot read property 'getURI' of undefined

```
At /C:/Users/Administrator/.atom/packages/sass-autocompile/lib/sass-autocompile.coffee:374

TypeError: Cannot read property 'getURI' of undefined
    at Object.module.exports.compileToFile (file:///C:/Users/Administrator/.atom/packages/sass-autocompile/lib/sass-autocompile.coffee:361:36)
    at atom-workspace.subscriptions.add.atom.commands.add.sass-autocompile:compile-to-file (file:///C:/Users/Administrator/.atom/packages/sass-autocompile/lib/sass-autocompile.coffee:318:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.7.4\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.7.4\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Administrator\AppData\Local\atom\app-1.7.4\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Administrator\AppData\Local\atom\app-1.7.4\resources\app.asar\src\atom-environment.js:1100:28)
    at EventEmitter.outerCallback (C:\Users\Administrator\AppData\Local\atom\app-1.7.4\resources\app.asar\src\application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -0:01.0 sass-autocompile:compile-to-file (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atomatigit"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "sass-autocompile": {}
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.14.1
atomic-chrome, v0.3.0
autoclose-html, v0.23.0
browser-plus, v0.0.60
color-picker, v2.1.1
docblockr, v0.7.3
file-type-icons, v1.3.0
language-diff, v0.4.0
linter, v1.11.4
minimap, v4.24.2
pigments, v0.27.1
sass-autocompile, v0.12.6
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by armin-pfaeffle** [comment]
Can you test 0.12.7?
