### ISSUE TITLE
spawn cmd.exe ENOENT

### ISSUE THREAD

**Issue by harudagondi** [armin-pfaeffle/sass-autocompile#76]
Having issues with sass-autocompile.

Win7

Added C:\Windows\System32 in %PATH%
Installed node-sass with -g
Path to 'node-sass' command:
``

node-sass --version >nul 2>&1 && (echo found) || (echo fail)
Output: `found`

```
var exec = require('child_process').exec;
var command = 'echo "test"';
exec(command, { env: Object.create(process.env) }, function(a, b, c) {
    console.log(a);
    console.log(b);
    console.log(c);
});
```

Output:

```
ChildProcess {domain: null, _events: Object, _eventsCount: 2, _maxListeners: undefined, _closesNeeded: 3…}
_closesGot: 3
_closesNeeded: 3
_events: Object
_eventsCount: 2
_handle: null
_maxListeners: undefined
connected: false
domain: null
exitCode: -4058
killed: false
pid: undefined
signalCode: null
spawnargs: Array[4]
spawnfile: "cmd.exe"
stderr: Socket
stdin: Socket
stdio: Array[3]
stdout: Socket
__proto__: ChildProcess
```

```
var exec = require('child_process').exec;
var command = 'node-sass --version >nul 2>&1 && (echo found) || (echo fail)';
exec(command, { env: Object.create(process.env) }, function(a, b, c) {
    console.log(a);
    console.log(b);
    console.log(c);
});
```

Output:

```
ChildProcess {domain: null, _events: Object, _eventsCount: 2, _maxListeners: undefined, _closesNeeded: 3…}
_closesGot: 3
_closesNeeded: 3
_events: Object
_eventsCount: 2
_handle: null
_maxListeners: undefined
connected: false
domain: null
exitCode: -4058
killed: false
pid: undefined
signalCode: null
spawnargs: Array[4]
spawnfile: "cmd.exe"
stderr: Socket
stdin: Socket
stdio: Array[3]
stdout: Socket
__proto__: ChildProcess
```

```
var exec = require('child_process').exec;
var command = 'node --version';
exec(command, { env: Object.create(process.env) }, function(a, b, c) {
    console.log(a);
    console.log(b);
    console.log(c);
});
```

Output:

```
ChildProcess {domain: null, _events: Object, _eventsCount: 2, _maxListeners: undefined, _closesNeeded: 3…}
_closesGot: 3
_closesNeeded: 3
_events: Object
_eventsCount: 2
_handle: null
_maxListeners: undefined
connected: false
domain: null
exitCode: -4058
killed: false
pid: undefined
signalCode: null
spawnargs: Array[4]
spawnfile: "cmd.exe"
stderr: Socket
stdin: Socket
stdio: Array[3]
stdout: Socket
```

https://github.com/armin-pfaeffle/sass-autocompile/issues/63
`Replace compiler.coffee`
Output:

```
Object {command: "node-sass --output-style compressed --indent-type …MMING\PROJECTS\lexically\static\css\main.min.css"", environment: Object}command: "node-sass --output-style compressed --indent-type space --indent-width 2 --precision 5 "D:\PROGRAMMING\PROJECTS\lexically\static\css\main.scss" "D:\PROGRAMMING\PROJECTS\lexically\static\css\main.min.css""environment: Object__proto__: ObjectALLUSERSPROFILE: "C:\ProgramData"AMDAPPSDKROOT: "C:\Program Files (x86)\AMD APP\"APPDATA: "C:\Users\<User>\AppData\Roaming"ATOM_HOME: "C:\Users\<User>\.atom"CLASSPATH: ".;C:\Program Files (x86)\Java\jre7\lib\ext\QTJava.zip"COMPUTERNAME: "<NAME>"ComSpec: "C:\Windows\system32\cmd.exe"CommonProgramFiles: "C:\Program Files (x86)\Common Files"CommonProgramFiles(x86): "C:\Program Files (x86)\Common Files"CommonProgramW6432: "C:\Program Files\Common Files"FP_NO_HOST_CHECK: "NO"GOOGLE_API_KEY: "<GAK>"HOMEDRIVE: "C:"HOMEPATH: "\Users\<User>"LOCALAPPDATA: "C:\Users\<User>\AppData\Local"LOGONSERVER: "\\<NAME>"NODE_ENV: "production"NODE_PATH: "C:\Users\<User>\AppData\Local\atom\app-1.7.4\resources\app.asar\exports"NUMBER_OF_PROCESSORS: "2"OS: "Windows_NT"PATH: "/usr/local/bin:"PATHEXT: ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW;.PY"PROCESSOR_ARCHITECTURE: "x86"PROCESSOR_ARCHITEW6432: "AMD64"PROCESSOR_IDENTIFIER: "AMD64 Family 15 Model 107 Stepping 2, AuthenticAMD"PROCESSOR_LEVEL: "15"PROCESSOR_REVISION: "6b02"PROMPT: "$P$G"PSModulePath: "C:\Windows\system32\WindowsPowerShell\v1.0\Modules\"PUBLIC: "C:\Users\Public"Path: "C:\Python34\;C:\Python34\Scripts;C:\Ruby22\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\<User>\AppData\Local\atom\bin;C:\Users\<User>\AppData\Roaming\npm;C:\Windows\System32"ProgramData: "C:\ProgramData"ProgramFiles: "C:\Program Files (x86)"ProgramFiles(x86): "C:\Program Files (x86)"ProgramW6432: "C:\Program Files"QTJAVA: "C:\Program Files (x86)\Java\jre7\lib\ext\QTJava.zip"SESSIONNAME: "Console"SystemDrive: "C:"SystemRoot: "C:\Windows"TEMP: "C:\Users\<User>\AppData\Local\Temp"TMP: "C:\Users\<User>\AppData\Local\Temp"USERDOMAIN: "<NAME>"USERNAME: "<User>"USERPROFILE: "C:\Users\<User>"VS120COMNTOOLS: "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\"windir: "C:\Windows"__proto__: Object__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: get __proto__()set __proto__: set __proto__()
compiler.coffee:552 Error: spawn cmd.exe ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

**Comment by armin-pfaeffle** [comment]
Well, it seems your Atom cannot execute `cmd.exe`.

Which version of Atom do you use?
You use Windows, right? Which one?
Have you cleared `Path to node-sass command` completely? There are no characters at all, even no spaces?

**Comment by harudagondi** [comment]
> Which version of Atom do you use?

1.7.4

> You use Windows, right? Which one?

Windows 7

> Have you cleared Path to node-sass command completely? There are no characters at all, even no spaces?

Yup. No characters at all.

**Comment by armin-pfaeffle** [comment]
Can you execute `process.env.Path` in Atom console and post the result? I'm pretty sure that `C:\Windows\system32\` is missing in the path list.

What other plugins do you use? Perhaps [python-tools](https://github.com/MichaelAquilina/python-tools/)?

Some other plugins modifies the internal variable `process.env.Path` so that my package cannot access executables from system32-folder.

**Comment by armin-pfaeffle** [comment]
Any updates?
